from . import constants as consts


reply_templates = {
    consts.RPL_WELCOME: 'Welcome to the Internet Relay Network {nickname}!{username}@{host}',
    consts.RPL_YOURHOST: 'Your host is {host}, running version {version}',
    consts.RPL_CREATED: 'This server was created {date}',
    consts.RPL_MYINFO: '{servername} {version} {available_user_modes} {available_channel_modes}',
    consts.RPL_BOUNCE: 'Try server {server_name}, port {port_number}',
    consts.RPL_USERHOST: None,
    consts.RPL_ISON: None,
    consts.RPL_AWAY: '{nick} :{away_message}',
    consts.RPL_UNAWAY: ':You are no longer marked as being away',
    consts.RPL_NOWAWAY: ':You have been marked as being away',
    consts.RPL_WHOISUSER: '{nick} {user} {host} * :{real_name}',
    consts.RPL_WHOISSERVER: '{nick} {server} :{server_info}',
    consts.RPL_WHOISOPERATOR: '{nick} :is an IRC operator',
    consts.RPL_WHOISSIDLE: '{nick} {integer} :seconds idle',
    consts.RPL_ENDOFWHOIS: '{nick} :End of WHOIS list',
    consts.RPL_WHOISCHANNELS: None,
    consts.RPL_WHOWASUSER: '{nick} {user} {host} * :{real_name}',
    consts.RPL_ENDOFWHOWAS: '{nick} :End of WHOWAS',
    consts.RPL_LIST: '{channel} {visible} :{topic}',
    consts.RPL_LISTEND: ':End of LIST',
    consts.RPL_UNIQOPIS: '{channel} {nickname}',
    consts.RPL_CHANNELMODEIS: '{channel} {mode} {mode_params}',
    consts.RPL_NOTOPIC: '{channel} :No topic is set',
    consts.RPL_TOPIC: '{channel} :{topic}',
    consts.RPL_INVITING: '{channel} {nick}',
    consts.RPL_SUMMONING: '{user} :Summoning user to IRC',
    consts.RPL_INVITELIST: '{channel} {invitemask}',
    consts.RPL_ENDOFINVITELIST: '{channel} :End of channel invite list',
    consts.RPL_EXCEPTLIST: '{channel} {exceptionmask}',
    consts.RPL_ENDOFEXCEPTLIST: '{channel} :End of channel exception list',
    consts.RPL_VERSION: '{version}.{debuglevel} {server} :{comments}',
    consts.RPL_WHOREPLY: '{channel} {user} {host} {server} {nick} {flags} :{hop_count} {real_name}',
    consts.RPL_ENDOFWHO: '{name} :End of WHO list',
    consts.RPL_NAMREPLY: None,
    consts.RPL_ENDOFNAMES: '{channel} :End of NAMES list',
    consts.RPL_LINKS: '{mask} {server} :{hopcount} {server_info}',
    consts.RPL_ENDOFLINKS: '{mask} :End of LINKS list',
    consts.RPL_BANLIST: '{channel} {banmask}',
    consts.RPL_ENDOFBANLIST: '{channel} :End of channel ban list',
    consts.RPL_INFO: ':{string}',
    consts.RPL_ENDOFINFO: ':End of INFO list',
    consts.RPL_MOTDSTART: ':- {server} Message of the day - ',
    consts.RPL_MOTD: ':- {text}',
    consts.RPL_ENDOFMOTD: ':End of MOTD command',
    consts.RPL_YOUREOPER: ':You are now an IRC operator',
    consts.RPL_REHASHING: '{config_file} :Rehashing',
    consts.RPL_YOURESERVICE: 'You are service {servicename}',
    consts.RPL_TIME: "{server} :{string showing server's local time}",
    consts.RPL_USERSSTART: ':UserID   Terminal  Host',
    consts.RPL_USERS: ':{username} {ttyline} {hostname}',
    consts.RPL_ENDOFUSERS: ':End of users',
    consts.RPL_NOUSERS: ':Nobody logged in',
    consts.RPL_TRACELINK: (
        'Link {version_debug_level} {destination} {next_server} V{protocol_version} '
        '{link uptime in seconds} {backstream_sendq} {upstream_sendq}'
    ),
    consts.RPL_TRACECONNECTING: 'Try. {class} {server}',
    consts.RPL_TRACEHANDSHAKE: 'H.S. {class} {server}',
    consts.RPL_TRACEUNKNOWN: '???? {class} [{client IP address in dot form}]',
    consts.RPL_TRACEOPERATOR: 'Oper {class} {nick}',
    consts.RPL_TRACEUSER: 'User {class} {nick}',
    consts.RPL_TRACESERVER: (
        'Serv {class} {int}S {int}C {server} {nick!user|*!*}@{host|server} '
        'V{protocol_version}'
    ),
    consts.RPL_TRACESERVICE: 'Service {class} {name} {type} {active_type}',
    consts.RPL_TRACENEWTYPE: '{newtype} 0 {client_name}',
    consts.RPL_TRACECLASS: 'Class {class} {count}',
    consts.RPL_TRACELOG: 'File {logfile} {debug_level}',
    consts.RPL_TRACEEND: '{server_name} {version & debug level} :End of TRACE',
    consts.RPL_STATSLINKINFO: (
        '{linkname} {sendq} {sent_messages} {sent_kbytes} {received_messages} '
        '{received_kbytes} {time_open}'
    ),
    consts.RPL_STATSCOMMANDS: '{command} {count} {byte_count} {remote_count}',
    consts.RPL_ENDOFSTATS: '{stats_letter} :End of STATS report',
    consts.RPL_STATSUPTIME: ':Server Up %d days %d:%02d:%02d',
    consts.RPL_STATSOLINE: 'O {hostmask} * {name}',
    consts.RPL_UMODEIS: '{user_mode_string}',
    consts.RPL_SERVLIST: '{name} {server} {mask} {type} {hopcount} {info}',
    consts.RPL_SERVLISTEND: '{mask} {type} :End of service listing',
    consts.RPL_LUSERCLIENT: ':There are {integer} users and {integer} services on {integer} servers',
    consts.RPL_LUSEROP: '{integer} :operator(s) online',
    consts.RPL_LUSERUNKNOWN: '{integer} :unknown connection(s)',
    consts.RPL_LUSERCHANNELS: '{integer} :channels formed',
    consts.RPL_LUSERME: ':I have {integer} clients and {integer} servers',
    consts.RPL_ADMINME: '{server} :Administrative info',
    consts.RPL_ADMINLOC1: ':{admin_info}',
    consts.RPL_ADMINLOC2: ':{admin_info}',
    consts.RPL_ADMINEMAIL: ':{admin_info}',
    consts.RPL_TRYAGAIN: '{command} :Please wait a while and try again.',
    consts.ERR_NOSUCHNICK: '{nickname} :No such nick/channel',
    consts.ERR_NOSUCHSERVER: '{server_name} :No such server',
    consts.ERR_NOSUCHCHANNEL: '{channel_name} :No such channel',
    consts.ERR_CANNOTSENDTOCHAN: '{channel_name} :Cannot send to channel',
    consts.ERR_TOOMANYCHANNELS: '{channel_name} :You have joined too many channels',
    consts.ERR_WASNOSUCHNICK: '{nickname} :There was no such nickname',
    consts.ERR_TOOMANYTARGETS: '{target} :{code} recipients. {message}',
    consts.ERR_NOSUCHSERVICE: '{service_name} :No such service',
    consts.ERR_NOORIGIN: ':No origin specified',
    consts.ERR_NORECIPIENT: ':No recipient given ({command})',
    consts.ERR_NOTEXTTOSEND: ':No text to send',
    consts.ERR_NOTOPLEVEL: '{mask} :No toplevel domain specified',
    consts.ERR_WILDTOPLEVEL: '{mask} :Wildcard in toplevel domain',
    consts.ERR_BADMASK: '{mask} :Bad Server/host mask',
    consts.ERR_UNKNOWNCOMMAND: '{command} :Unknown command',
    consts.ERR_NOMOTD: ':MOTD File is missing',
    consts.ERR_NOADMININFO: '{server} :No administrative info available',
    consts.ERR_FILEERROR: ':File error doing {file_op} on {file}',
    consts.ERR_NONICKNAMEGIVEN: ':No nickname given',
    consts.ERR_ERRONEUSNICKNAME: '{nick} :Erroneous nickname',
    consts.ERR_NICKNAMEINUSE: '{nick} :Nickname is already in use',
    consts.ERR_NICKCOLLISION: '{nick} :Nickname collision KILL from {user@{host}',
    consts.ERR_UNAVAILRESOURCE: '{nick/channel} :Nick/channel is temporarily unavailable',
    consts.ERR_USERNOTINCHANNEL: "{nick} {channel} :They aren't on that channel",
    consts.ERR_NOTONCHANNEL: "{channel} :You're not on that channel",
    consts.ERR_USERONCHANNEL: '{user} {channel} :is already on channel',
    consts.ERR_NOLOGIN: '{user} :User not logged in',
    consts.ERR_SUMMONDISABLED: ':SUMMON has been disabled',
    consts.ERR_USERSDISABLED: ':USERS has been disabled',
    consts.ERR_NOTREGISTERED: ':You have not registered',
    consts.ERR_NEEDMOREPARAMS: '{command} :Not enough parameters',
    consts.ERR_ALREADYREGISTRED: ':Unauthorized command (already registered)',
    consts.ERR_NOPERMFORHOST: ":Your host isn't among the privileged",
    consts.ERR_PASSWDMISMATCH: ':Password incorrect',
    consts.ERR_YOUREBANNEDCREEP: ':You are banned from this server',
    consts.ERR_YOUWILLBEBANNED: '',
    consts.ERR_KEYSET: '{channel} :Channel key already set',
    consts.ERR_CHANNELISFULL: '{channel} :Cannot join channel (+l)',
    consts.ERR_UNKNOWNMODE: '{char} :is unknown mode char to me for {channel}',
    consts.ERR_INVITEONLYCHAN: '{channel} :Cannot join channel (+i)',
    consts.ERR_BANNEDFROMCHAN: '{channel} :Cannot join channel (+b)',
    consts.ERR_BADCHANNELKEY: '{channel} :Cannot join channel (+k)',
    consts.ERR_BADCHANMASK: '{channel} :Bad Channel Mask',
    consts.ERR_NOCHANMODES: "{channel} :Channel doesn't support modes",
    consts.ERR_BANLISTFULL: '{channel} {char} :Channel list is full',
    consts.ERR_NOPRIVILEGES: ":Permission Denied- You're not an IRC operator",
    consts.ERR_CHANOPRIVSNEEDED: "{channel} :You're not channel operator",
    consts.ERR_CANTKILLSERVER: ":You can't kill a server!",
    consts.ERR_RESTRICTED: ':Your connection is restricted!',
    consts.ERR_UNIQOPPRIVSNEEDED: ":You're not the original channel operator",
    consts.ERR_NOOPERHOST: ':No O-lines for your host',
    consts.ERR_UMODEUNKNOWNFLAG: ':Unknown MODE flag',
    consts.ERR_USERSDONTMATCH: ':Cannot change mode for other users',
}
