# ruff: noqa: F401
# flake8: noqa: F401
from omlish import lang as _lang


with _lang.auto_proxy_init(globals()):
    ##

    from textual import app  # noqa
    from textual import binding  # noqa
    from textual import events  # noqa
    from textual import widgets  # noqa
    from textual.app import ActionError  # noqa
    from textual.app import ActiveModeError  # noqa
    from textual.app import App  # noqa
    from textual.app import AppError  # noqa
    from textual.app import AutopilotCallbackType  # noqa
    from textual.app import CallThreadReturnType  # noqa
    from textual.app import CommandCallback  # noqa
    from textual.app import ComposeResult  # noqa
    from textual.app import InvalidModeError  # noqa
    from textual.app import InvalidThemeError  # noqa
    from textual.app import ModeError  # noqa
    from textual.app import RenderResult  # noqa
    from textual.app import ReturnType  # noqa
    from textual.app import ScreenError  # noqa
    from textual.app import ScreenStackError  # noqa
    from textual.app import ScreenType  # noqa
    from textual.app import SuspendNotSupported  # noqa
    from textual.app import SystemCommand  # noqa
    from textual.app import UnknownModeError  # noqa
    from textual.app import get_system_commands_provider  # noqa
    from textual.binding import ActiveBinding  # noqa
    from textual.binding import Binding  # noqa
    from textual.binding import BindingError  # noqa
    from textual.binding import BindingIDString  # noqa
    from textual.binding import BindingType  # noqa
    from textual.binding import BindingsMap  # noqa
    from textual.binding import InvalidBinding  # noqa
    from textual.binding import KeyString  # noqa
    from textual.binding import Keymap  # noqa
    from textual.binding import KeymapApplyResult  # noqa
    from textual.binding import NoBinding  # noqa
    from textual.events import Action  # noqa
    from textual.events import AppBlur  # noqa
    from textual.events import AppFocus  # noqa
    from textual.events import Blur  # noqa
    from textual.events import Callback  # noqa
    from textual.events import Click  # noqa
    from textual.events import Compose  # noqa
    from textual.events import CursorPosition  # noqa
    from textual.events import DeliveryComplete  # noqa
    from textual.events import DeliveryFailed  # noqa
    from textual.events import DescendantBlur  # noqa
    from textual.events import DescendantFocus  # noqa
    from textual.events import Enter  # noqa
    from textual.events import Event  # noqa
    from textual.events import Focus  # noqa
    from textual.events import Hide  # noqa
    from textual.events import Idle  # noqa
    from textual.events import InputEvent  # noqa
    from textual.events import Key  # noqa
    from textual.events import Leave  # noqa
    from textual.events import Load  # noqa
    from textual.events import Mount  # noqa
    from textual.events import MouseCapture  # noqa
    from textual.events import MouseDown  # noqa
    from textual.events import MouseEvent  # noqa
    from textual.events import MouseMove  # noqa
    from textual.events import MouseRelease  # noqa
    from textual.events import MouseScrollDown  # noqa
    from textual.events import MouseScrollLeft  # noqa
    from textual.events import MouseScrollRight  # noqa
    from textual.events import MouseScrollUp  # noqa
    from textual.events import MouseUp  # noqa
    from textual.events import Paste  # noqa
    from textual.events import Print  # noqa
    from textual.events import Ready  # noqa
    from textual.events import Resize  # noqa
    from textual.events import ScreenResume  # noqa
    from textual.events import ScreenSuspend  # noqa
    from textual.events import Show  # noqa
    from textual.events import Timer  # noqa
    from textual.events import Unmount  # noqa
    from textual.widget import Widget  # noqa
    from textual.widgets import Button  # noqa
    from textual.widgets import Checkbox  # noqa
    from textual.widgets import Collapsible  # noqa
    from textual.widgets import CollapsibleTitle  # noqa
    from textual.widgets import ContentSwitcher  # noqa
    from textual.widgets import DataTable  # noqa
    from textual.widgets import Digits  # noqa
    from textual.widgets import DirectoryTree  # noqa
    from textual.widgets import Footer  # noqa
    from textual.widgets import Header  # noqa
    from textual.widgets import HelpPanel  # noqa
    from textual.widgets import Input  # noqa
    from textual.widgets import KeyPanel  # noqa
    from textual.widgets import Label  # noqa
    from textual.widgets import Link  # noqa
    from textual.widgets import ListItem  # noqa
    from textual.widgets import ListView  # noqa
    from textual.widgets import LoadingIndicator  # noqa
    from textual.widgets import Log  # noqa
    from textual.widgets import Markdown  # noqa
    from textual.widgets import MarkdownViewer  # noqa
    from textual.widgets import MaskedInput  # noqa
    from textual.widgets import OptionList  # noqa
    from textual.widgets import Placeholder  # noqa
    from textual.widgets import Pretty  # noqa
    from textual.widgets import ProgressBar  # noqa
    from textual.widgets import RadioButton  # noqa
    from textual.widgets import RadioSet  # noqa
    from textual.widgets import RichLog  # noqa
    from textual.widgets import Rule  # noqa
    from textual.widgets import Select  # noqa
    from textual.widgets import SelectionList  # noqa
    from textual.widgets import Sparkline  # noqa
    from textual.widgets import Static  # noqa
    from textual.widgets import Switch  # noqa
    from textual.widgets import Tab  # noqa
    from textual.widgets import TabPane  # noqa
    from textual.widgets import TabbedContent  # noqa
    from textual.widgets import Tabs  # noqa
    from textual.widgets import TextArea  # noqa
    from textual.widgets import Tooltip  # noqa
    from textual.widgets import Tree  # noqa
    from textual.widgets import Welcome  # noqa
