#!/bin/sh
set -e

SCRIPT_PATH=$(cd -- "$(dirname -- "$0")" && pwd)
SCRIPT_PATH="$SCRIPT_PATH/$(basename -- "$0")"
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")

exec "$SCRIPT_DIR/python" -m omdev.cli --cli-pkg-root "$SCRIPT_DIR" "$@"
