#!/bin/bash
set -e

if [ $(uname) == "Linux" ] && (cat /proc/mounts | egrep '^[^ ]+ / ' | grep '/docker/' > /dev/null) ; then
    VENV=.venv-docker
else
    VENV=.venv
fi

VENV_PYTHON_PATH="${BASH_SOURCE%/*}/$VENV/bin/python"
if [ -f "$VENV_PYTHON_PATH" ] ; then
    PYTHON="$VENV_PYTHON_PATH"
elif command -v python3 &> /dev/null ; then
    PYTHON=python3
else
    PYTHON=python
fi

if [ $# -eq 0 ] && "$PYTHON" -c "import IPython" 2> /dev/null ; then
    "$PYTHON" -m IPython
else
    "$PYTHON" "$@"
fi
