from ....dtypes import String
from ....tabledefs.elements import Column
from ....tabledefs.elements import CreatedAtUpdatedAt
from ....tabledefs.elements import Elements
from ....tabledefs.elements import IdIntegerPrimaryKey
from ....tabledefs.elements import Index
from ....tabledefs.lower import lower_table_elements
from ....tabledefs.tabledefs import TableDef
from ..tabledefs import PostgresStatementRenderer


def test_render_golden():
    tbl = lower_table_elements(TableDef('users', Elements(
        IdIntegerPrimaryKey(),
        CreatedAtUpdatedAt(),
        Column('name', String()),
        Index(['name']),
    )))

    assert PostgresStatementRenderer().render_create_statements(tbl) == [
        (
            'create table users (\n'
            '  id bigint generated by default as identity not null,\n'
            '  created_at timestamp with time zone not null default current_timestamp,\n'
            '  updated_at timestamp with time zone not null default current_timestamp,\n'
            '  name text not null,\n'
            '  primary key (id)\n'
            ')'
        ),
        'create index  users__index__name on users (name)\n',
        (
            'create or replace function users__function__updated_at__updated_at()\n'
            'returns trigger\n'
            'language plpgsql\n'
            'as $$\n'
            'begin\n'
            '  if new.updated_at is not distinct from old.updated_at then\n'
            '    new.updated_at := current_timestamp;\n'
            '  end if;\n'
            '\n'
            '  return new;\n'
            'end;\n'
            '$$'
        ),
        (
            'create trigger users__trigger__updated_at__updated_at\n'
            'before update on users\n'
            'for each row\n'
            'execute function users__function__updated_at__updated_at()\n'
        ),
    ]
