from ...dtypes import Boolean
from ...dtypes import Bytes
from ...dtypes import Datetime
from ...dtypes import Float
from ...dtypes import Integer
from ...dtypes import String
from ...dtypes import Uuid
from ...tabledefs.diffing import AlterColumn
from ...tabledefs.elements import Column
from ...tabledefs.elements import PrimaryKey
from ...tabledefs.elements import UpdatedAtTrigger
from ...tabledefs.rendering import StatementRenderer
from ...tabledefs.tabledefs import TableDef


##


CREATE_UPDATED_AT_TRIGGER_FUNCTION_SRC = """\
create or replace function {function_name}()
returns trigger
language plpgsql
as $$
begin
  if new.{column_name} is not distinct from old.{column_name} then
    new.{column_name} := current_timestamp;
  end if;

  return new;
end;
$$\
"""


CREATE_UPDATED_AT_TRIGGER_SRC = """\
create trigger {trigger_name}
before update on {table_name}
for each row
execute function {function_name}()
"""


CREATE_UPDATED_AT_TRIGGER_IF_NOT_EXISTS_SRC = """\
do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = '{trigger_name}'
      and tgrelid = '{table_name}'::regclass
  ) then
    create trigger {trigger_name}
    before update on {table_name}
    for each row
    execute function {function_name}();
  end if;
end
$$\
"""


class PostgresStatementRenderer(StatementRenderer):
    def column_type(self, c: Column, *, is_identity: bool, indexed: bool = False) -> str:
        if isinstance(c.type, String):
            return 'text'
        elif isinstance(c.type, Uuid):
            return 'uuid'
        elif isinstance(c.type, Integer):
            return 'bigint' if is_identity else 'integer'
        elif isinstance(c.type, Datetime):
            return 'timestamp with time zone'
        elif isinstance(c.type, Boolean):
            return 'boolean'
        elif isinstance(c.type, Float):
            return 'double precision'
        elif isinstance(c.type, Bytes):
            return 'bytea'
        else:
            raise TypeError(c.type)

    def column_identity_sql(self, c: Column) -> str:
        return 'generated by default as identity'

    def drop_statement(self, tbl: TableDef) -> str:
        return f'drop table if exists {tbl.name} cascade'

    def alter_column_statements(self, op: AlterColumn) -> list[str]:
        c = op.column
        nn = 'set' if not c.nullable else 'drop'
        return [
            f'alter table {op.table} alter column {c.name} type {self.column_type(c, is_identity=False)}',
            f'alter table {op.table} alter column {c.name} {nn} not null',
        ]

    def updated_at_trigger_statements(
            self,
            tbl: TableDef,
            e: UpdatedAtTrigger,
            pk: PrimaryKey | None,
            opts: StatementRenderer.CreateOptions,
    ) -> list[str]:
        function_name = f'{tbl.name}__function__updated_at__{e.column}'
        trigger_name = f'{tbl.name}__trigger__updated_at__{e.column}'

        return [
            CREATE_UPDATED_AT_TRIGGER_FUNCTION_SRC.format(
                function_name=function_name,
                column_name=e.column,
            ),
            (
                CREATE_UPDATED_AT_TRIGGER_IF_NOT_EXISTS_SRC
                if opts.if_not_exists
                else CREATE_UPDATED_AT_TRIGGER_SRC
            ).format(
                function_name=function_name,
                trigger_name=trigger_name,
                table_name=tbl.name,
            ),
        ]
