base_image = 'ubuntu:24.04'

user = 'om'

dep_sets = [
    'system',
    'python',
    'x11',
]

jdks = [
    'zulu21-ca-jdk',
    'zulu25-ca-jdk',
    'zulu26-ca-jdk',
]

nvm_versions = [
    '20',
    '22',
    '24',
    '26',
]

rbenv_versions = [
    '3.4',
    '4.0',
]

uv_python_versions = [
    '3.8',
    '3.9',
    '3.10',
    '3.11',
    '3.12',
    '3.13',
    '3.14',
    '3.14+freethreaded',
]

pyenv_version_keys = [
    '8',
    '13',
    '14',
    '14t',
    '15',
    '15t',
]

workdir = '/work'

[cache_mounts]
'pip' = '/om/.cache/pip'
'uv' = '/om/.cache/uv'
