base_image = 'ubuntu:24.04'

user = 'omlish'

dep_sets = [
    'system',
    'python',
    'x11',
]

jdks = [
    'zulu21-ca-jdk',
    'zulu25-ca-jdk',
    'zulu26-ca-jdk',
]

nvm_versions = [
    '20',
    '22',
    '25',
]

rbenv_versions = [
    '3.4',
    '4.0',
]

uv_python_versions = [
    '3.13',
    '3.14',
]

pyenv_version_keys = [
    '8',
    '13',
    '14',
]

config_files = [
    '.gdbinit',
    '.tmux.conf',
    '.vimrc',
]

workdir = '/work'

[cache_mounts]
'pip' = '/omlish/.cache/pip'
'uv' = '/omlish/.cache/uv'
