services:

  # dev

  omlish-dev: &dev
    build:
      context: '../'
      dockerfile: 'docker/dev/Dockerfile'
    restart: 'unless-stopped'
    cap_add:
      - 'SYS_PTRACE'
    security_opt:
      - 'apparmor:unconfined'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '..:/omlish'
    depends_on: &dev-deps
      - 'omlish-mysql'
      - 'omlish-postgres'
      - 'omlish-s3'
      # ext
      - 'omlish-elasticsearch'
      # - 'omlish-neo4j'
      - 'omlish-pgvector'
      - 'omlish-redis'
    links: *dev-deps
    expose:
      - '22'
      - '8000'
    ports:
      - '35220:8000'
      - '35221:22'

  omlish-dev-amd64:
    <<: *dev
    platform: 'linux/x86_64'
    expose:
      - '22'
      - '8000'
    ports:
      - '35222:8000'
      - '35223:22'

  # ci

  omlish-ci:
    build: '.'
    image: 'wrmsr/omlish-ci:latest'
    platform: 'linux/x86_64'
    restart: 'no'
    depends_on: &ci-deps
      - 'omlish-mysql'
      - 'omlish-postgres'
      - 'omlish-s3'
    links: *ci-deps

  # main

  omlish-postgres:
    image: 'postgres:17.2'
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'omlish'
    expose:
      - '5432'
    ports:
      - '35224:5432'

  omlish-mysql:
    image: 'mysql:9.1.0'
    restart: 'unless-stopped'
    environment:
      MYSQL_USER: 'omlish'
      MYSQL_PASSWORD: 'omlish'
      MYSQL_ROOT_PASSWORD: 'omlish'
    expose:
      - '3306'
    ports:
      - '35225:3306'

  omlish-s3:
    image: 'adobe/s3mock:3.12.0'
    restart: 'unless-stopped'
    expose:
      - '9090'
      - '9191'
    ports:
      - '35226:9090'
      - '35227:9191'

  # ext

  omlish-elasticsearch:
    image: 'elasticsearch:8.16.1'
    restart: 'unless-stopped'
    environment:
      ES_JAVA_OPTS: '-Xms750m -Xmx750m'
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
    expose:
      - '9200'
    ports:
      - '35228:9200'

  omlish-neo4j:
    image: 'neo4j:5.26.0-community'
    restart: 'unless-stopped'
    environment:
      NEO4J_AUTH: 'none'
    expose:
      - '7474'
      - '7687'
    ports:
      - '35229:7474'
      - '35230:7687'

  omlish-pgvector:
    image: 'pgvector/pgvector:0.8.0-pg17'
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'omlish'
    expose:
      - '5432'
    ports:
      - '35231:5432'

  omlish-redis:
    image: 'redis:7.4.1'
    restart: 'unless-stopped'
    expose:
      - '6379'
    ports:
      - '35232:6379'
