services:

  omlish-dev: &_dev
    build:
      context: '../'
      dockerfile: 'docker/dev/Dockerfile'
    restart: 'unless-stopped'
    cap_add:
      - 'SYS_PTRACE'
    security_opt:
      - 'apparmor:unconfined'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '..:/omlish'
    depends_on:
      - 'omlish-mysql'
      - 'omlish-postgres'
      - 'omlish-redis'
      - 'omlish-s3'
    links:
      - 'omlish-mysql'
      - 'omlish-postgres'
      - 'omlish-redis'
      - 'omlish-s3'
    expose:
      - '22'
      - '8000'
    ports:
      - '35220:8000'
      - '35221:22'

  omlish-dev-amd64:
    <<: *_dev
    platform: 'linux/x86_64'
    expose:
      - '22'
      - '8000'
    ports:
      - '35222:8000'
      - '35223:22'

  omlish-ci:
    build: '.'
    image: 'wrmsr/omlish-ci:latest'
    platform: 'linux/x86_64'
    restart: 'no'
    depends_on:
      - 'omlish-postgres'
    links:
      - 'omlish-postgres'

  omlish-mysql:
    image: 'mysql:9.0.1'
    restart: 'unless-stopped'
    environment:
      MYSQL_USER: 'omlish'
      MYSQL_PASSWORD: 'omlish'
      MYSQL_ROOT_PASSWORD: 'omlish'
    expose:
      - '3306'
    ports:
      - '35224:3306'

  omlish-postgres:
    image: 'postgres:16.3'
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: 'omlish'
      POSTGRES_PASSWORD: 'omlish'
    expose:
      - '5432'
    ports:
      - '35225:5432'

  omlish-redis:
    image: 'redis:7.4.0'
    restart: 'unless-stopped'
    expose:
      - '6379'
    ports:
      - '35226:6379'

  omlish-s3:
    image: 'adobe/s3mock:3.10.0'
    restart: 'unless-stopped'
    expose:
      - '9090'
      - '9191'
    ports:
      - '35227:9090'
      - '35228:9191'
