version: '3'

services:

  omlish-mysql:
    image: 'mysql:8'
    restart: 'unless-stopped'
    environment:
      MYSQL_USER: 'omlish'
      MYSQL_PASSWORD: 'omlish'
      MYSQL_ROOT_PASSWORD: 'omlish'
    expose:
      - '3306'
    ports:
      - '34230:3306'

  omlish-postgres:
    image: 'postgres:16'
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: 'omlish'
      POSTGRES_PASSWORD: 'omlish'
    expose:
      - '5432'
    ports:
      - '34231:5432'
