version: '3'

services:

  omlish-postgres:
    image: 'postgres:15.3'
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: 'omlish'
      POSTGRES_PASSWORD: 'omlish'
    expose:
      - '5432'
    ports:
      - '34231:5432'
