version: '3'

services:

  omlish-dev: &_dev
    build:
      context: '../'
      dockerfile: 'docker/dev/Dockerfile'
    restart: 'unless-stopped'
    cap_add:
      - 'SYS_PTRACE'
    security_opt:
      - 'apparmor:unconfined'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '..:/omlish'
    depends_on:
      - 'omlish-mysql'
      - 'omlish-postgres'
    links:
      - 'omlish-mysql'
      - 'omlish-postgres'
    expose:
      - '8000'
    ports:
      - '33220:8000'

  omlish-dev-amd64:
    <<: *_dev
    platform: 'linux/x86_64'
    expose:
      - '8000'
    ports:
      - '35220:8000'

  omlish-mysql:
    image: 'mysql:8'
    restart: 'unless-stopped'
    environment:
      MYSQL_USER: 'omlish'
      MYSQL_PASSWORD: 'omlish'
      MYSQL_ROOT_PASSWORD: 'omlish'
    expose:
      - '3306'
    ports:
      - '35221:3306'

  omlish-postgres:
    image: 'postgres:16'
    restart: 'unless-stopped'
    environment:
      POSTGRES_USER: 'omlish'
      POSTGRES_PASSWORD: 'omlish'
    expose:
      - '5432'
    ports:
      - '35222:5432'
