[build-system]
requires = [
    'setuptools',
]
build-backend = 'setuptools.build_meta'

[project]
name = 'omml'
authors = [
    {name = 'wrmsr'},
]
urls = {source = 'https://github.com/wrmsr/omlish'}
license = {text = 'BSD-3-Clause'}
requires-python = '>=3.12'
version = '0.0.0.dev8'
classifiers = [
    'License :: OSI Approved :: BSD License',
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Developers',
    'Operating System :: OS Independent',
    'Operating System :: POSIX',
]
description = 'omml'
dependencies = [
    'omlish == 0.0.0.dev8',
]

[project.optional-dependencies]
torch = [
    'torch >= 2.4',
]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = [
    'omml',
    'omml.*',
]
exclude = [
    '*.tests',
    '*.tests.*',
]
