; Minisql, semantic ABNF rewrite with explicit skip handling.
;
; Notes:
; - This is character-level ABNF, so S/R are used explicitly.
; - Consume the whole input with: single-stmt = S select S ";" S
; - regular-ident must not match reserved keywords, except that
;   "left" and "right" are explicitly permitted as unquoted identifiers,
;   matching the ANTLR grammar.

SKIP = WS / comment
S    = *SKIP      ; optional
R    = 1*SKIP     ; required


; =========================
; Top level
; =========================

single-stmt = S select S ";" S

select = query-expression

query-expression =
    [with-clause R]
    query-term
    *(S union-op R query-term)

with-clause =
    "with" R cte *(S "," S cte)

cte =
    ident R "as" S "(" S select S ")"

union-op =
    "union" [R set-quantifier]

query-term =
    query-specification

query-specification =
    "select" R
    [set-quantifier R]
    select-list
    [R from-clause]
    [R where-clause]
    [R group-by-clause]
    [R having-clause]
    [R order-by-clause]

select-list =
    select-item *(S "," S select-item)

select-item =
    "*"
  / expr [R select-item-alias]

select-item-alias =
    ["as" R] ident

from-clause =
    "from" R table-reference *(S "," S table-reference)

where-clause =
    "where" R expr

group-by-clause =
    "group" R "by" R grouping-element *(S "," S grouping-element)

grouping-element =
    expr

having-clause =
    "having" R expr

order-by-clause =
    "order" R "by" R sort-item *(S "," S sort-item)

sort-item =
    expr [R direction]

direction =
    "asc" / "desc"


; =========================
; Expressions
; =========================

expr =
    or-expr

or-expr =
    and-expr *(R "or" R and-expr)

and-expr =
    not-expr *(R "and" R not-expr)

not-expr =
    ["not" R] predicate-expr

predicate-expr =
    concat-expr
    [ cmp-predicate
    / is-null-predicate
    / in-list-predicate
    / in-select-predicate
    / like-predicate
    ]

cmp-predicate =
    S cmp-op S concat-expr

is-null-predicate =
    R "is" R ["not" R] null-literal

in-list-predicate =
    (R "in" / R "not" R "in")
    S "(" S expr-list S ")"

in-select-predicate =
    (R "in" / R "not" R "in")
    S "(" S select S ")"

like-predicate =
    (R "like" / R "not" R "like")
    R concat-expr

expr-list =
    expr *(S "," S expr)

concat-expr =
    additive-expr *(S "||" S additive-expr)

additive-expr =
    multiplicative-expr *(S ("+" / "-") S multiplicative-expr)

multiplicative-expr =
    unary-expr *(S ("*" / "/" / "%") S unary-expr)

unary-expr =
    *(unary-op S) cast-expr

unary-op =
    "+" / "-"

cast-expr =
    primary-expr *(S "::" S ident)

primary-expr =
    function-call
  / star-function-call
  / case-expr
  / scalar-subquery
  / parenthesized-expr
  / simple-expr

function-call =
    qualified-name
    S "(" S [expr-list S] ")"
    [S over-clause]

star-function-call =
    qualified-name
    S "(" S "*" S ")"
    [S over-clause]

case-expr =
    "case"
    *(R case-item)
    [R "else" R expr]
    R "end"

case-item =
    "when" R expr R "then" R expr

scalar-subquery =
    "(" S select S ")"

parenthesized-expr =
    "(" S expr S ")"

over-clause =
    "over" S "(" S [order-by-clause-inner] S ")"

order-by-clause-inner =
    "order" R "by" R sort-item *(S "," S sort-item)

simple-expr =
    qualified-name
  / number
  / string
  / null-literal
  / true-literal
  / false-literal


; =========================
; Relations / FROM items
; =========================

table-reference =
    joined-table

joined-table =
    table-factor
    *(R [join-type R] "join" R table-factor [R "on" R expr])

table-factor =
    table-primary [R alias-clause]

alias-clause =
    ["as" R] ident

table-primary =
    qualified-name
  / "(" S select S ")"
  / "(" S joined-table S ")"

join-type =
    "inner"
  / "left" [R "outer"]
  / "right" [R "outer"]
  / "full" [R "outer"]
  / "cross"
  / "natural"


; =========================
; Names / literals
; =========================

qualified-name =
    ident *(S "." S ident)

ident-list =
    ident *(S "," S ident)

ident =
    quoted-ident / unquoted-ident

unquoted-ident =
    "left"
  / "right"
  / regular-ident

quoted-ident =
    DQUOTE *(quoted-ident-char / DQUOTE DQUOTE) DQUOTE

regular-ident =
    ident-start *ident-char

ident-start =
    ALPHA / "_"

ident-char =
    ALPHA / DIGIT / "_" / "@" / ":" / "$"

number =
    float-value / decimal-value / integer-value

integer-value =
    1*DIGIT

decimal-value =
    (1*DIGIT "." *DIGIT)
  / ("." 1*DIGIT)

float-value =
    (1*DIGIT ["." *DIGIT] exponent)
  / ("." 1*DIGIT exponent)

exponent =
    ("e" / "E") ["+" / "-"] 1*DIGIT

string =
    squote *(string-char / squote squote) squote

null-literal =
    "null"

true-literal =
    "true"

false-literal =
    "false"

set-quantifier =
    "distinct" / "all"

cmp-op =
    "=" / "!=" / "<>" / "<=" / "<" / ">=" / ">"


; =========================
; Skipping / comments
; =========================

comment =
    line-comment / block-comment

line-comment =
    "--" *not-eol [CR] [LF]

block-comment =
    "/*" *block-comment-unit "*/"

block-comment-unit =
    block-comment-non-star
  / "*" block-comment-non-slash

block-comment-non-star =
    %x00-29 / %x2B-7F

block-comment-non-slash =
    %x00-2E / %x30-7F

not-eol =
    %x00-09 / %x0B-0C / %x0E-7F

WS =
    SP / HTAB / CR / LF


; =========================
; Character classes
; =========================

string-char =
    %x00-26 / %x28-7F

quoted-ident-char =
    %x00-21 / %x23-7F

squote =
    %x27

DQUOTE =
    %x22