deps = [
  # packaging
  'apt-transport-https',
  'ca-certificates',
  'software-properties-common',

  # base system
  'dumb-init',
  'gosu',
  'lsb-release',
  'sudo',

  # filesystem
  'bindfs',

  # networking & network diagnostics
  'aria2',
  'bmon',
  'curl',
  'dnsutils',
  'iputils-ping',
  'iputils-tracepath',
  'mosh',
  'net-tools',
  'netcat-openbsd',
  'openssh-server',
  'socat',
  'tcpdump',
  'telnet',
  'wget',

  # build essentials & compilers
  'autoconf',
  'build-essential',
  'clang',
  'cmake',
  'g++',
  'g++-14',
  'gcc',
  'gcc-14',
  'llvm',
  'make',
  'pkg-config',

  # libs
  'libncurses5-dev',
  'libreadline6-dev',
  'libssl-dev',

  # language toolchains & runtimes
  'maven',
  'perl',
  'ruby',

  # parsers, generators & compiler tooling
  'bison',
  'flex',
  'protobuf-compiler',
  'xsltproc',

  # version control systems
  'cvs',
  'git',
  'mercurial',
  'subversion',

  # debugging, tracing & profiling
  'gdb',
  'lsof',
  'strace',

  # sandboxing
  'bubblewrap',

  # data formats
  'jq',
  'libyaml-dev',

  # databases
  'libdb-dev',
  'libgdbm6',
  'libpq-dev',
  'libsqlite3-dev',
  'postgresql-client',
  'sqlite3',

  # terminal UX & interactive tools
  'btop',
  'htop',
  'less',
  'moreutils',
  'ncdu',
  'ripgrep',
  'silversearcher-ag',
  'tmux',

  # shells
  'tcsh',
  'zsh',

  # editors & shells
  'emacs',
  'nano',
  'vim',

  # crypto, auth & trust
  'gnupg',
  'gnupg-agent',

  # documentation & introspection
  'file',
  'graphviz',
  'man-db',

  # chat & communication
  'irssi',

  # archiving & compression
  'libbz2-dev',
  'liblz4-dev',
  'lz4',
  'lzma',
  'lzma-dev',
  'unzip',
  'zip',

  # multiarch dev
  'binutils-aarch64-linux-gnu',
  'binutils-multiarch',
  'binutils-riscv64-linux-gnu',
  'binutils-x86-64-linux-gnu',
  'capstone-tool',
  'file',
  'gdb-multiarch',
  'lld',
  'opensbi',
  'ovmf',
  'qemu-efi-aarch64',
  'qemu-efi-riscv64',
  'qemu-system-arm',
  'qemu-system-misc',
  'qemu-system-x86',
  'qemu-user',
  'qemu-utils',
  'u-boot-qemu',

]
