daemon off;
error_log /home/ec2-user/www/error.log;
pid /home/ec2-user/www/nginx.pid;
user www-data www-data;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location / {
            root /www-data;
        }

        access_log /home/ec2-user/www/access.log;
    }

    server {
        #------- Start SSL config with http2 support ----#
        # listen 443 http2;
        # server_name theos.in;
        # ssl on;
        # ssl_certificate /etc/nginx/ssl/theos.in/theos.in.cer;
        # ssl_certificate_key /etc/nginx/ssl/theos.in/theos.in.key;
        # ssl_session_timeout 30m;
        # ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        # ssl_ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+A ESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;
        # ssl_session_cache shared:SSL:10m;
        # ssl_dhparam /etc/nginx/ssl/theos.in/dhparams.pem;
        # ssl_prefer_server_ciphers on;

        # ## Improves TTFB by using a smaller SSL buffer than the nginx default
        # ssl_buffer_size 8k;

        # ## Enables OCSP stapling
        # ssl_stapling on;
        # resolver 8.8.8.8;
        # ssl_stapling_verify on;

        # ## Send header to tell the browser to prefer https to http traffic
        # add_header Strict-Transport-Security max-age=31536000;

        # ## SSL logs ##
        # access_log /var/log/nginx/theos.in/ssl_access.log;
        # error_log /var/log/nginx/theos.in/ssl_error.log;
        # #-------- END SSL config -------##

        # # Add rest of your config below like document path and more ##

        listen 443 ssl;

        server_name         lt;
        ssl_certificate     /home/ec2-user/www/lt.cer;
        ssl_certificate_key /home/ec2-user/www/lt.key;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location /hello {
            proxy_pass  http://127.0.0.1:8000/;
        }

        location / {
            root /www-data;
        }

        access_log /home/ec2-user/www/access.log;
    }
}
