SD_JOURNAL_LOCAL_ONLY = 1 << 0
SD_JOURNAL_RUNTIME_ONLY = 1 << 1
SD_JOURNAL_SYSTEM = 1 << 2
SD_JOURNAL_CURRENT_USER = 1 << 3
SD_JOURNAL_OS_ROOT = 1 << 4
SD_JOURNAL_ALL_NAMESPACES = 1 << 5
SD_JOURNAL_INCLUDE_DEFAULT_NAMESPACE = 1 << 6

SD_JOURNAL_NOP = 0
SD_JOURNAL_APPEND = 1
SD_JOURNAL_INVALIDATE = 2
